function [ kEc ] = reduction_Factor( T, option )
%This Function caculates the reduction factor kEc for the modulus of elasticity
% of concrete according the EuroCode.
%   T is the elevated temperature 
n=length(T);
kEc=zeros(n,1);
m=1;
if nargin < 2
    option = 'Silicieux';
end
switch option
    case 'Silicieux'
        while m<=n
            if T(m)<=20 
                kEc(m)=1;
            elseif T(m)<=20 
                kEc(m)=1;
            elseif T(m)<=100 
                a=20;
                b=100;
                fa=1;
                fb=0.625;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=200 
                a=100;
                b=200;
                fa=0.625;
                fb=0.432;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=300 
                a=200;
                b=300;
                fa=0.432;
                fb=0.304;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=400 
                a=300;
                b=400;
                fa=0.304;
                fb=0.188;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=500 
                a=400;
                b=500;
                fa=0.188;
                fb=0.1;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=600 
                a=500;
                b=600;
                fa=0.1;
                fb=0.045;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=700 
                a=600;
                b=700;
                fa=0.045;
                fb=0.03;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=800 
                a=700;
                b=800;
                fa=0.03;
                fb=0.015;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=900 
                a=800;
                b=900;
                fa=0.015;
                fb=0.008;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=1000 
                a=900;
                b=1000;
                fa=0.008;
                fb=0.004;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);        
            elseif T(m)<=1100 
                a=1000;
                b=1100;
                fa=0.004;
                fb=0.001;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=1200 
                a=1100;
                b=1200;
                fa=0.001;
                fb=0;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            end
            m=m+1;
        end
    case 'Calcaire'
        while m<=n
            if T(m)<=20 
                kEc(m)=1;
            elseif T(m)<=20 
                kEc(m)=1;
            elseif T(m)<=100 
                a=20;
                b=100;
                fa=1;
                fb=0.625;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=200 
                a=100;
                b=200;
                fa=0.625;
                fb=0.441;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=300 
                a=200;
                b=300;
                fa=0.441;
                fb=0.325;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=400 
                a=300;
                b=400;
                fa=0.325;
                fb=0.213;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=500 
                a=400;
                b=500;
                fa=0.213;
                fb=0.123;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=600 
                a=500;
                b=600;
                fa=0.123;
                fb=0.06;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=700 
                a=600;
                b=700;
                fa=0.06;
                fb=0.043;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=800 
                a=700;
                b=800;
                fa=0.043;
                fb=0.027;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=900 
                a=800;
                b=900;
                fa=0.027;
                fb=0.015;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=1000 
                a=900;
                b=1000;
                fa=0.015;
                fb=0.006;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);        
            elseif T(m)<=1100 
                a=1000;
                b=1100;
                fa=0.006;
                fb=0.002;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            elseif T(m)<=1200 
                a=1100;
                b=1200;
                fa=0.002;
                fb=0;
                kEc(m)=fa+(fb-fa)/(b-a)*(T(m)-a);
            end
            m=m+1;
        end
end
end

